const title = (name, detail = 'จัดการข้อมูลและติดตามผลการดำเนินงาน') => `<section class="module-head"><div><h1>${name}</h1><p>${detail}</p></div><button class="primary" data-export>⇩ ดาวน์โหลด CSV</button></section>`;
const cards = (items) => `<div class="module-cards">${items.map(([label,value,tone]) => `<article class="${tone || ''}"><span>${label}</span><strong>${value}</strong><small>อัปเดตล่าสุดวันนี้</small></article>`).join('')}</div>`;
const form = (heading, fields) => `<section class="work-panel"><h2>${heading}</h2><form data-demo-save><div class="form-grid">${fields.map(([label,type='text',options]) => `<label>${label}${type === 'select' ? `<select required>${options.map(x => `<option>${x}</option>`).join('')}</select>` : `<input type="${type}" required />`}</label>`).join('')}</div><div class="form-actions"><button type="reset" class="secondary">ล้างข้อมูล</button><button class="primary">บันทึกข้อมูล</button></div></form></section>`;
const list = (heading, rows) => `<section class="work-panel"><div class="panel-top"><h2>${heading}</h2><input class="table-search" placeholder="ค้นหาข้อมูล" data-filter /></div><table class="module-table"><thead><tr><th>รายการ</th><th>รายละเอียด</th><th>สถานะ</th><th>ดำเนินการ</th></tr></thead><tbody>${rows.map((r,i) => `<tr><td>${r[0]}</td><td>${r[1]}</td><td><mark class="${r[2]}">${r[3]}</mark></td><td><button class="table-action" data-demo-action="${i}">ดูรายละเอียด</button></td></tr>`).join('')}</tbody></table></section>`;
const commonRows = [['DS-2567-001','ไข้เลือดออก · ต.บางนาค','green','ควบคุมโรคแล้ว'],['DS-2567-002','หัด · ต.กะลุวอ','blue','อยู่ระหว่างดำเนินการ'],['DS-2567-003','HFMD · ต.ลำภู','gold','รอตรวจสอบ']];
export const diseaseMeta = { 'ไข้เลือดออก':{color:'#e23d4f',fields:['ไข้สูง','ปวดศีรษะ/ปวดกระบอกตา','จุดเลือดออก','ผล NS1 / IgM']}, 'ไข้หวัดใหญ่':{color:'#2a73d9',fields:['ไข้','ไอ','เจ็บคอ','ผลตรวจ Influenza']}, 'หัด':{color:'#8b55c8',fields:['ไข้','ผื่น','ไอ/น้ำมูก/ตาแดง','ประวัติวัคซีน MMR']}, 'อีสุกอีใส':{color:'#e88c20',fields:['ไข้','ผื่นแดง','ตุ่มน้ำใส/ตุ่มหนอง','ประวัติวัคซีน']}, 'วัณโรค':{color:'#19a57a',fields:['ไอต่อเนื่อง','น้ำหนักลด','ผลเสมหะ/GenXpert','สถานที่รักษา']}, 'มือเท้าปาก':{color:'#dd5b9e',fields:['แผลในปาก','ผื่นมือ/เท้า','สถานศึกษา','ผล RT-PCR']}};
export const diseaseFields = disease => (diseaseMeta[disease]?.fields || []).map(x => `<label>${x}<select><option>ไม่ทราบ</option><option>ไม่มี</option><option>มี</option></select></label>`).join('');
const investigation = () => `${title('แบบสอบสวนโรคออนไลน์','กรอกข้อมูลผู้ป่วย เลือกโรค และบันทึกตำแหน่งเพื่อแสดงบนแผนที่')} <section class="investigation-layout"><form class="work-panel" data-investigation-form><h2>1. ข้อมูลผู้ป่วยและตำแหน่ง</h2><div class="form-grid"><label>โรค<select data-disease required>${Object.keys(diseaseMeta).map(x=>`<option>${x}</option>`).join('')}</select></label><label>ชื่อ-สกุลผู้ป่วย<input name="patient" required /></label><label>HN<input name="hn" required /></label><label>อายุ<input name="age" type="number" required /></label><label>วันที่เริ่มป่วย<input name="onset" type="date" required /></label><label>ตำบล/อำเภอ<input name="location" required /></label><label>ละติจูด<input name="lat" type="number" step="any" value="6.425" required /></label><label>ลองจิจูด<input name="lng" type="number" step="any" value="101.825" required /></label></div><h2>2. รายละเอียดเฉพาะโรค</h2><div class="form-grid" data-disease-fields>${diseaseFields('ไข้เลือดออก')}</div><h2>3. ผู้สอบสวน</h2><div class="form-grid"><label>ชื่อผู้สอบสวน<input name="investigator" required /></label><label>หมายเลขโทรศัพท์<input name="phone" type="tel" /></label><label>ผลการรักษา<select name="outcome"><option>กำลังรักษา</option><option>หาย</option><option>ส่งต่อ</option><option>เสียชีวิต</option></select></label></div><div class="form-actions"><button type="reset" class="secondary">ล้างข้อมูล</button><button class="primary">บันทึกและปักหมุด</button></div></form><aside class="case-map work-panel"><div class="panel-top"><div><h2>แผนที่เคสสอบสวน</h2><small>สีหมุดแยกตามโรค</small></div><button class="table-action" data-clear-pins>ล้างหมุด</button></div><div class="map-canvas" data-case-map><span class="map-label">จังหวัดนราธิวาส</span></div><div class="map-legend">${Object.entries(diseaseMeta).map(([n,m])=>`<span><i style="background:${m.color}"></i>${n}</span>`).join('')}</div><div data-map-details class="map-details">ยังไม่มีข้อมูลที่บันทึก</div></aside></section>`;

export function moduleView(id) {
  if (id === 'executive') return `${title('Dashboard ผู้บริหาร','ภาพรวมผลการดำเนินงานสำหรับผู้บริหาร')} ${cards([['KPI ผ่านเกณฑ์','5/6','green'],['เคสค้างดำเนินการ','3','orange'],['การแจ้งเตือนระดับสูง','2','red'],['ความครบถ้วนรายงาน 506','96%','blue']])} ${list('ประเด็นที่ต้องติดตาม',commonRows)}`;
  if (id === 'epidemiology') return `${title('Dashboard ระบาดวิทยา','วิเคราะห์แนวโน้มและเหตุการณ์เฝ้าระวัง')} ${cards([['โรคที่พบสูงสุด','ไข้หวัดใหญ่','blue'],['อัตราป่วยสัปดาห์นี้','42.6','orange'],['Cluster ที่เปิดอยู่','3','red']])} ${list('เหตุการณ์เฝ้าระวัง',commonRows)}`;
  if (id === 'hosxp') return `${title('นำเข้าข้อมูล HOSxP','ตรวจสอบและนำเข้ารายการผู้ป่วยเข้าสู่ระบบ')} ${form('ค้นหารายการนำเข้า',[['วันที่เริ่มต้น','date'],['วันที่สิ้นสุด','date'],['ประเภทบริการ','select',['OPD','IPD','ER']]])} ${list('รายการที่รอประมวลผล',commonRows)}`;
  if (id === 'investigation') return investigation();
  if (id === 'tracking') return `${title('ติดตามและควบคุมโรค','อัปเดตความคืบหน้าและผลการควบคุมโรค')} ${cards([['รอรับทราบ','12','gold'],['กำลังดำเนินการ','15','blue'],['ควบคุมแล้ว','30','green']])} ${list('เคสติดตาม',commonRows)}`;
  if (id === 'alerts') return `${title('ระบบแจ้งเตือน','สร้าง ติดตาม และปิดการแจ้งเตือน')} ${form('สร้างการแจ้งเตือน',[['หัวข้อแจ้งเตือน'],['ระดับความรุนแรง','select',['ปกติ','เฝ้าระวัง','วิกฤต']],['รายละเอียด']])} ${list('การแจ้งเตือนที่เปิดอยู่',[['ALT-001','พบผู้ป่วยโรคหัด 1 ราย','red','วิกฤต'],['ALT-002','ไข้เลือดออกเพิ่มขึ้น 30%','orange','เฝ้าระวัง'],['ALT-003','วัณโรคขาดนัด','gold','รอตรวจสอบ']])}`;
  if (id === 'report506') return `${title('รายงาน 506','จัดทำ ตรวจสอบ และส่งรายงานเฝ้าระวังโรค')} ${form('จัดทำรายงาน 506',[['สัปดาห์ระบาดวิทยา','number'],['โรค','select',['ไข้เลือดออก','หัด','ไข้หวัดใหญ่','HFMD']],['จำนวนผู้ป่วย','number']])} ${list('รายงานที่ส่งแล้ว',commonRows)}`;
  if (id === 'lab') return `${title('รายงานห้องปฏิบัติการ','บันทึกและติดตามผลตรวจทางห้องปฏิบัติการ')} ${form('เพิ่มผลตรวจ',[['เลขที่สิ่งส่งตรวจ'],['ประเภทการตรวจ','select',['Influenza A','COVID-19','Dengue NS1','AFB Smear']],['ผลตรวจ','select',['Positive','Negative','รอตรวจสอบ']]])} ${list('ผลตรวจล่าสุด',commonRows)}`;
  if (id === 'management') return `${title('รายงานผู้บริหาร','สรุปผลสำหรับการประชุมและการตัดสินใจ')} ${cards([['รายงานรออนุมัติ','4','gold'],['รายงานพร้อมส่ง','12','green'],['รายงานประจำเดือน','8','blue']])} ${list('รายงานที่จัดทำ',commonRows)}`;
  if (id === 'export') return `${title('Export Report','เลือกข้อมูลสำหรับดาวน์โหลดเป็น CSV')} ${form('ตั้งค่าการส่งออก',[['ชุดข้อมูล','select',['เคสเฝ้าระวัง','รายงาน 506','ผล LAB','การแจ้งเตือน']],['วันที่เริ่มต้น','date'],['วันที่สิ้นสุด','date']])} <section class="work-panel"><h2>ส่งออกข้อมูล</h2><p>กดปุ่มด้านบนเพื่อดาวน์โหลดรายงานตัวอย่างในรูปแบบ CSV</p><button class="primary" data-export>ดาวน์โหลดรายงาน</button></section>`;
  if (id === 'settings') return `${title('ตั้งค่า / ผู้ดูแลระบบ','กำหนดค่าระบบและการเชื่อมต่อข้อมูล')} ${form('การตั้งค่าการเชื่อมต่อ',[['ชื่อหน่วยงาน'],['อีเมลผู้ดูแล','email'],['เวลาซิงก์ข้อมูล','select',['ทุก 15 นาที','ทุก 30 นาที','ทุก 1 ชั่วโมง']]])} <section class="work-panel"><h2>สถานะระบบ</h2><p>HOSxP และ LAB: <b class="ok">เชื่อมต่อแล้ว</b></p><p>Supabase: กำหนด publishable key และ access token ใน runtime-config.js ก่อนใช้งานข้อมูลจริง</p></section>`;
  return '';
}

