import { getDashboardData } from './services/dashboard-service.js';
import { shell } from './components/layout.js'; import { metricsGrid } from './components/metrics.js'; import { analytics } from './components/charts.js'; import { caseTracking } from './components/case-tracking.js'; import { rightRail } from './components/alerts.js'; import { moduleView, diseaseMeta, investigationForm } from './components/modules.js';
const data = await getDashboardData();
const dashboard = `<div class="page"><div class="dashboard">${metricsGrid(data.metrics)}${analytics()}${caseTracking(data.cases)}<section class="kpis">${[['รับทราบภายใน 24 ชม.','98%'],['ควบคุมโรคเสร็จภายใน 3 วัน','95%'],['เวลาเฉลี่ยรับรายงานเคส','2 ชม. 15 นาที'],['เวลาเฉลี่ยปิดเคส','2 วัน 8 ชม.'],['เคสค้างดำเนินการ','3 เคส']].map(x=>`<b>${x[0]}<strong>${x[1]}</strong></b>`).join('')}</section></div>${rightRail(data.alerts)}</div>`;
document.querySelector('#app').innerHTML = shell(dashboard);
const root = document.querySelector('#module-root');
const showToast = message => { const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.append(toast); setTimeout(() => toast.remove(), 2600); };
const exportCsv = () => { const rows = [['เลขที่เคส','โรค','ผู้ป่วย','พื้นที่','สถานะ'], ...data.cases.map(x => [x[0],x[1],x[2],x[3],x[5]])]; const file = new Blob([rows.map(x => x.map(v => `"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(file); link.download = 'ndss-report.csv'; link.click(); URL.revokeObjectURL(link.href); showToast('ดาวน์โหลดรายงาน CSV แล้ว'); };
document.addEventListener('click', event => { const nav = event.target.closest('[data-view]'); if (nav) { const view = nav.dataset.view; root.innerHTML = view === 'dashboard' ? dashboard : `<div class="module-page">${moduleView(view)}</div>`; document.querySelectorAll('.nav-link').forEach(x => x.classList.toggle('active', x === nav)); if(view === 'investigation') setTimeout(renderPins,0); } if (event.target.closest('[data-export]')) exportCsv(); if (event.target.matches('[data-demo-action]')) showToast('เปิดรายละเอียดรายการแล้ว'); });
let investigationMap;
let activeDiseaseFilter = 'all';
const escapeHtml = value => String(value || '-').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const renderPins = () => { const mapNode = root.querySelector('[data-case-map]'); if (!mapNode) return; const cases = JSON.parse(localStorage.getItem('ndss-investigations') || '[]'); const visibleCases=activeDiseaseFilter === 'all' ? cases : cases.filter(item => item.disease === activeDiseaseFilter); root.querySelector('[data-total-cases]').textContent = cases.length; Object.keys(diseaseMeta).forEach(disease => { root.querySelector(`[data-disease-total="${disease}"]`).textContent = cases.filter(item => item.disease === disease).length; }); root.querySelectorAll('[data-map-filter]').forEach(card=>card.classList.toggle('active',card.dataset.mapFilter===activeDiseaseFilter)); root.querySelector('[data-map-filter-label]').textContent=activeDiseaseFilter==='all'?'Leaflet.js · แสดงทุกโรค':`Leaflet.js · แสดงเฉพาะ ${activeDiseaseFilter}`; if (!window.L) { mapNode.textContent = 'กำลังโหลดแผนที่ Leaflet...'; return; } if (investigationMap) investigationMap.remove(); investigationMap = window.L.map(mapNode,{scrollWheelZoom:false}).setView([6.426,101.825],12); window.L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(investigationMap); const bounds=[]; visibleCases.forEach((item,index) => { const lat=Number(item.lat) || 6.426 + (index % 4) * .008; const lng=Number(item.lng) || 101.825 + (index % 4) * .01; const color=diseaseMeta[item.disease]?.color || '#176fca'; const marker=window.L.circleMarker([lat,lng],{radius:10,color:'#fff',weight:3,fillColor:color,fillOpacity:1}).addTo(investigationMap); const detail=`<b>${escapeHtml(item.patient)}</b><br>${escapeHtml(item.disease)}<br>${escapeHtml(item.location)}<br><small>เริ่มป่วย ${escapeHtml(item.onset)} · ${lat.toFixed(5)}, ${lng.toFixed(5)}</small>`; marker.bindPopup(detail).on('click',()=>root.querySelector('[data-map-details]').innerHTML=detail); bounds.push([lat,lng]); }); if(bounds.length) investigationMap.fitBounds(bounds,{padding:[36,36],maxZoom:14}); investigationMap.on('click',event=>{ const lat=event.latlng.lat.toFixed(6), lng=event.latlng.lng.toFixed(6); const form=root.querySelector('[data-investigation-form]'); if(form?.elements.lat) form.elements.lat.value=lat; if(form?.elements.lng) form.elements.lng.value=lng; root.querySelector('[data-map-details]').textContent=`เลือกพิกัด ${lat}, ${lng} แล้ว — บันทึกแบบฟอร์มเพื่อปักหมุด`; }); root.querySelector('[data-map-details]').textContent = visibleCases.length ? `${visibleCases.length} เคสบนแผนที่ — คลิกหมุดหรือพื้นที่บนแผนที่เพื่อเลือกพิกัด` : 'ไม่พบเคสตามตัวกรองที่เลือก'; setTimeout(()=>investigationMap.invalidateSize(),100); };
document.addEventListener('submit', event => { if (event.target.matches('[data-demo-save]')) { event.preventDefault(); const records = JSON.parse(localStorage.getItem('ndss-drafts') || '[]'); records.push({ createdAt: new Date().toISOString(), values: [...new FormData(event.target).values()] }); localStorage.setItem('ndss-drafts', JSON.stringify(records)); event.target.reset(); showToast('บันทึกข้อมูลในเครื่องแล้ว — ตั้งค่า Supabase เพื่อบันทึกข้อมูลจริง'); } if (event.target.matches('[data-investigation-form]')) { event.preventDefault(); const value=Object.fromEntries(new FormData(event.target)); const records=JSON.parse(localStorage.getItem('ndss-investigations') || '[]'); records.push({...value,location:value.location || [value.subdistrict,value.district,value.province].filter(Boolean).join(' '),disease:event.target.querySelector('[data-disease]').value,createdAt:new Date().toISOString()}); localStorage.setItem('ndss-investigations',JSON.stringify(records)); renderPins(); showToast('บันทึกแบบสอบสวนและปักหมุดบนแผนที่แล้ว'); } });
document.addEventListener('change', event => { if(event.target.matches('[data-disease]')) { const disease=event.target.value; const meta=diseaseMeta[disease]; const template=root.querySelector('[data-template-download]'); template.href=`./public/forms/${encodeURIComponent(meta.template)}`; template.textContent=`เปิด PDF ต้นฉบับ: ${disease}`; root.querySelector('[data-template-pages]').innerHTML=Array.from({length:meta.pages},(_,i)=>`<img src="./public/form-pages/${encodeURIComponent(meta.template.replace('.pdf',''))}-${i+1}.png" alt="แบบฟอร์ม ${disease} หน้า ${i+1}" loading="lazy" />`).join(''); event.target.closest('[data-investigation-form]').outerHTML=investigationForm(disease); showToast(`เปลี่ยนเป็นแบบฟอร์ม ${disease} ตามต้นฉบับแล้ว`); } });
document.addEventListener('input', event => { if (event.target.matches('[data-filter]')) { const keyword = event.target.value.toLowerCase(); event.target.closest('.work-panel').querySelectorAll('tbody tr').forEach(row => row.hidden = !row.textContent.toLowerCase().includes(keyword)); } });
document.addEventListener('click', event => { const filter=event.target.closest('[data-map-filter]'); if(filter) { activeDiseaseFilter=filter.dataset.mapFilter; renderPins(); } if(event.target.matches('[data-clear-pins]')) { localStorage.removeItem('ndss-investigations'); activeDiseaseFilter='all'; renderPins(); } });
document.addEventListener('click', event => { if(event.target.closest('[data-print-report]')) window.print(); });

