import { getDashboardData } from './services/dashboard-service.js';
import { shell } from './components/layout.js'; import { metricsGrid } from './components/metrics.js'; import { analytics } from './components/charts.js'; import { caseTracking } from './components/case-tracking.js'; import { rightRail } from './components/alerts.js'; import { moduleView, diseaseFields, diseaseMeta } from './components/modules.js';
const data = await getDashboardData();
const dashboard = `<div class="page"><div class="dashboard">${metricsGrid(data.metrics)}${analytics()}${caseTracking(data.cases)}<section class="kpis">${[['รับทราบภายใน 24 ชม.','98%'],['ควบคุมโรคเสร็จภายใน 3 วัน','95%'],['เวลาเฉลี่ยรับรายงานเคส','2 ชม. 15 นาที'],['เวลาเฉลี่ยปิดเคส','2 วัน 8 ชม.'],['เคสค้างดำเนินการ','3 เคส']].map(x=>`<b>${x[0]}<strong>${x[1]}</strong></b>`).join('')}</section></div>${rightRail(data.alerts)}</div>`;
document.querySelector('#app').innerHTML = shell(dashboard);
const root = document.querySelector('#module-root');
const showToast = message => { const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.append(toast); setTimeout(() => toast.remove(), 2600); };
const exportCsv = () => { const rows = [['เลขที่เคส','โรค','ผู้ป่วย','พื้นที่','สถานะ'], ...data.cases.map(x => [x[0],x[1],x[2],x[3],x[5]])]; const file = new Blob([rows.map(x => x.map(v => `"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(file); link.download = 'ndss-report.csv'; link.click(); URL.revokeObjectURL(link.href); showToast('ดาวน์โหลดรายงาน CSV แล้ว'); };
document.addEventListener('click', event => { const nav = event.target.closest('[data-view]'); if (nav) { const view = nav.dataset.view; root.innerHTML = view === 'dashboard' ? dashboard : `<div class="module-page">${moduleView(view)}</div>`; document.querySelectorAll('.nav-link').forEach(x => x.classList.toggle('active', x === nav)); } if (event.target.closest('[data-export]')) exportCsv(); if (event.target.matches('[data-demo-action]')) showToast('เปิดรายละเอียดรายการแล้ว'); });
const renderPins = () => { const map = root.querySelector('[data-case-map]'); if (!map) return; const cases = JSON.parse(localStorage.getItem('ndss-investigations') || '[]'); map.querySelectorAll('.case-pin').forEach(x=>x.remove()); cases.forEach((item,i) => { const pin=document.createElement('button'); pin.className='case-pin'; pin.style.background=diseaseMeta[item.disease].color; pin.style.left=`${18+(i*19)%64}%`; pin.style.top=`${20+(i*23)%56}%`; pin.title=`${item.patient} · ${item.disease}`; pin.dataset.pin=i; map.append(pin); }); root.querySelector('[data-map-details]').textContent = cases.length ? `${cases.length} เคสบนแผนที่ — คลิกหมุดเพื่อดูรายละเอียด` : 'ยังไม่มีข้อมูลที่บันทึก'; };
document.addEventListener('submit', event => { if (event.target.matches('[data-demo-save]')) { event.preventDefault(); const records = JSON.parse(localStorage.getItem('ndss-drafts') || '[]'); records.push({ createdAt: new Date().toISOString(), values: [...new FormData(event.target).values()] }); localStorage.setItem('ndss-drafts', JSON.stringify(records)); event.target.reset(); showToast('บันทึกข้อมูลในเครื่องแล้ว — ตั้งค่า Supabase เพื่อบันทึกข้อมูลจริง'); } if (event.target.matches('[data-investigation-form]')) { event.preventDefault(); const value=Object.fromEntries(new FormData(event.target)); const records=JSON.parse(localStorage.getItem('ndss-investigations') || '[]'); records.push({...value,disease:event.target.querySelector('[data-disease]').value,createdAt:new Date().toISOString()}); localStorage.setItem('ndss-investigations',JSON.stringify(records)); renderPins(); showToast('บันทึกแบบสอบสวนและปักหมุดบนแผนที่แล้ว'); } });
document.addEventListener('change', event => { if(event.target.matches('[data-disease]')) { const disease=event.target.value; const meta=diseaseMeta[disease]; const template=root.querySelector('[data-template-download]'); template.href=`./public/forms/${encodeURIComponent(meta.template)}`; template.textContent=`เปิด PDF ต้นฉบับ: ${disease}`; root.querySelector('[data-template-pages]').innerHTML=Array.from({length:meta.pages},(_,i)=>`<img src="./public/form-pages/${encodeURIComponent(meta.template.replace('.pdf',''))}-${i+1}.png" alt="แบบฟอร์ม ${disease} หน้า ${i+1}" loading="lazy" />`).join(''); if (disease !== 'ไข้เลือดออก') showToast(`แสดงแม่แบบต้นฉบับของ ${disease} แล้ว`); } });
document.addEventListener('input', event => { if (event.target.matches('[data-filter]')) { const keyword = event.target.value.toLowerCase(); event.target.closest('.work-panel').querySelectorAll('tbody tr').forEach(row => row.hidden = !row.textContent.toLowerCase().includes(keyword)); } });
document.addEventListener('click', event => { if(event.target.matches('[data-clear-pins]')) { localStorage.removeItem('ndss-investigations'); renderPins(); } const pin=event.target.closest('[data-pin]'); if(pin) { const item=JSON.parse(localStorage.getItem('ndss-investigations')||'[]')[pin.dataset.pin]; root.querySelector('[data-map-details]').innerHTML=`<b>${item.patient}</b><br>${item.disease} · ${item.location}<br>พิกัด ${item.lat}, ${item.lng}<br>เริ่มป่วย ${item.onset}`; } });
document.addEventListener('click', event => { if(event.target.closest('[data-print-report]')) window.print(); });

